Fix for AutoFriend for geyser extension
rtm516/MCXboxBroadcast pull request #21
Opened 2023-04-06 23:24 UTC by PizzaThatCodes

Noticed that the Standalone has the option for AutoFriend and people wanted it on the extension one too, so here is a way for it, which also includes the api limitation for unfollow

2023-04-06 23:24 UTC, PizzaThatCodes commented
Fixes Autofriend for geyser extension

2023-04-10 11:18 UTC, rtm516 requested changes

2023-04-10 11:18 UTC, rtm516 commented on bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/MCXboxBroadcastExtension.java
> +            GeyserImpl.getInstance().getScheduledThread().scheduleAtFixedRate(this::autoFriend, config.friendSyncConfig.updateInterval, config.friendSyncConfig.updateInterval, TimeUnit.SECONDS);
This should only be added if one of the options is enabled. See https://github.com/rtm516/MCXboxBroadcast/blob/master/bootstrap/standalone/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/standalone/StandaloneMain.java#L101

2023-04-10 11:18 UTC, rtm516 commented on bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/MCXboxBroadcastExtension.java
> +
```suggestion
```

2023-04-10 11:18 UTC, rtm516 commented on bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/ExtensionConfig.java
> +    }
This should be moved to a more generic shared class to save duplicate code

2023-04-10 11:18 UTC, rtm516 commented on bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/MCXboxBroadcastExtension.java
> +
This should be moved to a more generic shared class to save duplicate code

2023-04-10 21:58 UTC, rtm516 requested changes

2023-04-10 21:58 UTC, rtm516 commented on bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/ExtensionConfig.java
> +
```suggestion
```

2023-04-10 21:58 UTC, rtm516 commented on bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/MCXboxBroadcastExtension.java
> +            friendConfig = new ObjectMapper(new YAMLFactory()).configure(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES, false).readValue(configFile, FriendConfig.class);
The second `friendConfig` shouldn't be needed

2023-04-10 21:58 UTC, rtm516 commented on bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/ExtensionConfig.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
Instead of this add the `friendSyncConfig` back

2023-04-10 21:58 UTC, rtm516 commented on bootstrap/standalone/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/standalone/StandaloneConfig.java
> -    public FriendSyncConfig friendSyncConfig;
Keep this

2023-04-10 21:58 UTC, rtm516 commented on bootstrap/standalone/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/standalone/StandaloneConfig.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
As mentioned previously dont do this and just keep `friendSyncConfig`

2023-04-10 21:58 UTC, rtm516 commented on bootstrap/standalone/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/standalone/StandaloneMain.java
> +            friendConfig = new ObjectMapper(new YAMLFactory()).configure(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES, false).readValue(configFile, FriendConfig.class);
See previous

2023-04-10 21:58 UTC, rtm516 commented on core/src/main/java/com/rtm516/mcxboxbroadcast/core/FriendConfig.java
> +    public FriendSyncConfig friendSyncConfig;
As previously mentioned this shouldnt be in here

2023-04-10 21:58 UTC, rtm516 commented on core/src/main/java/com/rtm516/mcxboxbroadcast/core/FriendConfig.java
> +    }
This should be its own class

2023-04-10 21:58 UTC, rtm516 commented on core/src/main/java/com/rtm516/mcxboxbroadcast/core/FriendConfig.java
> +public class FriendConfig {
Remove annotation and maybe rename FriendUtils

2023-04-10 21:58 UTC, rtm516 commented on core/src/main/java/com/rtm516/mcxboxbroadcast/core/FriendConfig.java
> +
```suggestion
    }
```

2023-04-10 23:00 UTC, PizzaThatCodes commented
When creating FriendUtils and removing the FriendConfig Variable from the one class it brought up an issue of trying to get the config's of the extension and standalone, so I moved their config files into a folder called "configs" inside the core directory which also includes the FriendSyncConfig to allow me to use those classes for the autoFriend() function.

2023-04-28 18:13 UTC, hasankayra04 commented
Any update on this?

2023-04-29 15:55 UTC, PizzaThatCodes commented
Currently waiting on rtm516 to either push this to the main branch, or to comment any issues.


Currently if you want to use the jar for this version you can use:
https://ci.rtm516.co.uk/job/MCXboxBroadcast/view/change-requests/job/PR-21/

2023-05-01 04:07 UTC, onebeastchris commented
Heyo! Unfortunately, ever since your last changes, i've been unable to actually get the friend listener to show up - Geyser logs the extension as existing & claims to laod it, however, it never prints anything in the console/starts up - this is now with the last build from the link; when you linked an initial build, that worked

2023-05-10 23:57 UTC, TBYT commented
> update: works just fine; fault was on Geysers end - now fixed with [GeyserMC/Geyser@b48d4a0](https://github.com/GeyserMC/Geyser/commit/b48d4a0625ed9a269d81fea6e535345bce01c0af)

is it fixed with geyser by using this pr of mcxboxbroadcast or without this pr?

2023-05-11 00:19 UTC, onebeastchris commented
The error wasn't coming from MCXboxBroadcast; it was on Geysers part and only in the edge case of running multiple extensions. This PR, and the normal version, should work just fine.

2023-05-11 03:40 UTC, TBYT commented
ok nevermind then

2023-06-12 03:37 UTC, SonnenPingu commented
Will it be possible to transfer this function to the 1.20 as well? It would be a shame if it was gone now.

2023-07-03 16:45 UTC, jefflima1 commented
Could you add this fix to new version? has been updated but the issue has not been merged

2023-07-21 07:28 UTC, Adamiok approved these changes
Looks fine to me.
Taking a long time to merge.

Sorry, wrong repo.

2023-08-06 10:55 UTC, merged